### ISSUE TITLE
Can't even build webtex

### ISSUE THREAD

**Issue by sheerun** [pkgw/webtex#7]
I tried, but got:

```
python dev-scripts/make-bundle.py data/packages.txt data/mapfiles.txt texcache build texpatches build/latex.dump.json
downloading cm ...
downloading cm-super ...
Traceback (most recent call last):
  File "dev-scripts/make-bundle.py", line 441, in <module>
    commandline (sys.argv)
  File "dev-scripts/make-bundle.py", line 437, in commandline
    b.go ()
  File "dev-scripts/make-bundle.py", line 61, in go
    self.load_package (zip, pkgname)
  File "dev-scripts/make-bundle.py", line 117, in load_package
    path = self.get_package (pkgname)
  File "dev-scripts/make-bundle.py", line 193, in get_package
    fn, headers = urllib.urlretrieve (url, cachepath)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 558, in open_ftp
    (fp, retrlen) = self.ftpcache[key].retrfile(file, type)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 906, in retrfile
    conn, retrlen = self.ftp.ntransfercmd(cmd)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ftplib.py", line 334, in ntransfercmd
    host, port = self.makepasv()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ftplib.py", line 312, in makepasv
    host, port = parse227(self.sendcmd('PASV'))
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ftplib.py", line 830, in parse227
    raise error_reply, resp
IOError: [Errno ftp error] 200 Type set to I
make: *** [build/glyph-encoding.json] Error 1
```

It seems some files you downloaded with FTP are gone..

**Comment by pkgw** [comment]
Hmm, that's a strange. The message that the FTP server is reporting isn't really an error message, so I'm not sure why ftplib is deciding there's a problem. I think at least some versions of ftplib might have a problem parsing multi-line responses from FTP servers, a problem I ran into with [conda](https://github.com/conda/conda/pull/4276).

That being said, be warned that Webtex is effectively on ice for the foreseeable future. I don't expect to continue developing it.

**Comment by sheerun** [comment]
I appreciate your work here anyway :)

For the time being I started using https://github.com/Khan/KaTeX instead
